// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.1
// source: dna.proto

package dna_server

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DNA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	A  string `protobuf:"bytes,2,opt,name=a,proto3" json:"a,omitempty"`
	O  string `protobuf:"bytes,3,opt,name=o,proto3" json:"o,omitempty"`
	D  string `protobuf:"bytes,4,opt,name=D,proto3" json:"D,omitempty"`
	T  string `protobuf:"bytes,5,opt,name=t,proto3" json:"t,omitempty"`
}

func (x *DNA) Reset() {
	*x = DNA{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dna_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DNA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNA) ProtoMessage() {}

func (x *DNA) ProtoReflect() protoreflect.Message {
	mi := &file_dna_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNA.ProtoReflect.Descriptor instead.
func (*DNA) Descriptor() ([]byte, []int) {
	return file_dna_proto_rawDescGZIP(), []int{0}
}

func (x *DNA) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DNA) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *DNA) GetO() string {
	if x != nil {
		return x.O
	}
	return ""
}

func (x *DNA) GetD() string {
	if x != nil {
		return x.D
	}
	return ""
}

func (x *DNA) GetT() string {
	if x != nil {
		return x.T
	}
	return ""
}

type DNARequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MutationRate float32 `protobuf:"fixed32,2,opt,name=mutationRate,proto3" json:"mutationRate,omitempty"`
	Target       string  `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *DNARequest) Reset() {
	*x = DNARequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dna_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DNARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNARequest) ProtoMessage() {}

func (x *DNARequest) ProtoReflect() protoreflect.Message {
	mi := &file_dna_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNARequest.ProtoReflect.Descriptor instead.
func (*DNARequest) Descriptor() ([]byte, []int) {
	return file_dna_proto_rawDescGZIP(), []int{1}
}

func (x *DNARequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DNARequest) GetMutationRate() float32 {
	if x != nil {
		return x.MutationRate
	}
	return 0
}

func (x *DNARequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type DNAResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Dna          *DNA   `protobuf:"bytes,2,opt,name=dna,proto3" json:"dna,omitempty"`
	Error        bool   `protobuf:"varint,3,opt,name=error,proto3" json:"error,omitempty"`
	Errormessage string `protobuf:"bytes,4,opt,name=errormessage,proto3" json:"errormessage,omitempty"`
}

func (x *DNAResponse) Reset() {
	*x = DNAResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dna_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DNAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNAResponse) ProtoMessage() {}

func (x *DNAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dna_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNAResponse.ProtoReflect.Descriptor instead.
func (*DNAResponse) Descriptor() ([]byte, []int) {
	return file_dna_proto_rawDescGZIP(), []int{2}
}

func (x *DNAResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DNAResponse) GetDna() *DNA {
	if x != nil {
		return x.Dna
	}
	return nil
}

func (x *DNAResponse) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *DNAResponse) GetErrormessage() string {
	if x != nil {
		return x.Errormessage
	}
	return ""
}

type ValidateDNARequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DnaString      string `protobuf:"bytes,1,opt,name=dnaString,proto3" json:"dnaString,omitempty"`
	OriginalTarget string `protobuf:"bytes,2,opt,name=original_target,json=originalTarget,proto3" json:"original_target,omitempty"`
}

func (x *ValidateDNARequest) Reset() {
	*x = ValidateDNARequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dna_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateDNARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateDNARequest) ProtoMessage() {}

func (x *ValidateDNARequest) ProtoReflect() protoreflect.Message {
	mi := &file_dna_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateDNARequest.ProtoReflect.Descriptor instead.
func (*ValidateDNARequest) Descriptor() ([]byte, []int) {
	return file_dna_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateDNARequest) GetDnaString() string {
	if x != nil {
		return x.DnaString
	}
	return ""
}

func (x *ValidateDNARequest) GetOriginalTarget() string {
	if x != nil {
		return x.OriginalTarget
	}
	return ""
}

type ValidateDNAResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *ValidateDNAResponse) Reset() {
	*x = ValidateDNAResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dna_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateDNAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateDNAResponse) ProtoMessage() {}

func (x *ValidateDNAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dna_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateDNAResponse.ProtoReflect.Descriptor instead.
func (*ValidateDNAResponse) Descriptor() ([]byte, []int) {
	return file_dna_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateDNAResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

var File_dna_proto protoreflect.FileDescriptor

var file_dna_proto_rawDesc = []byte{
	0x0a, 0x09, 0x64, 0x6e, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4d, 0x0a, 0x03, 0x44,
	0x4e, 0x41, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x61,
	0x12, 0x0c, 0x0a, 0x01, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x6f, 0x12, 0x0c,
	0x0a, 0x01, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x44, 0x12, 0x0c, 0x0a, 0x01,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x74, 0x22, 0x58, 0x0a, 0x0a, 0x44, 0x4e,
	0x41, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x75, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0c,
	0x6d, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x22, 0x6f, 0x0a, 0x0b, 0x44, 0x4e, 0x41, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x03, 0x64, 0x6e, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x04, 0x2e, 0x44, 0x4e, 0x41, 0x52, 0x03, 0x64, 0x6e, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x5b, 0x0a, 0x12, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x44, 0x4e, 0x41, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x64,
	0x6e, 0x61, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x64, 0x6e, 0x61, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x27, 0x0a, 0x0f, 0x6f, 0x72, 0x69,
	0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x54, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x22, 0x2b, 0x0a, 0x13, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x44, 0x4e,
	0x41, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x32,
	0x74, 0x0a, 0x13, 0x44, 0x6e, 0x61, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x44, 0x4e, 0x41,
	0x12, 0x0b, 0x2e, 0x44, 0x4e, 0x41, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e,
	0x44, 0x4e, 0x41, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x44, 0x4e, 0x41, 0x12, 0x13, 0x2e, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x44, 0x4e, 0x41, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x14, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x44, 0x4e, 0x41, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3f, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x57, 0x69, 0x7a, 0x65, 0x67, 0x65, 0x6e, 0x65, 0x46, 0x6f, 0x75, 0x6e,
	0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x57, 0x69, 0x7a, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x2f, 0x64, 0x6e, 0x61, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x3b, 0x64, 0x6e, 0x61, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dna_proto_rawDescOnce sync.Once
	file_dna_proto_rawDescData = file_dna_proto_rawDesc
)

func file_dna_proto_rawDescGZIP() []byte {
	file_dna_proto_rawDescOnce.Do(func() {
		file_dna_proto_rawDescData = protoimpl.X.CompressGZIP(file_dna_proto_rawDescData)
	})
	return file_dna_proto_rawDescData
}

var file_dna_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_dna_proto_goTypes = []interface{}{
	(*DNA)(nil),                 // 0: DNA
	(*DNARequest)(nil),          // 1: DNARequest
	(*DNAResponse)(nil),         // 2: DNAResponse
	(*ValidateDNARequest)(nil),  // 3: ValidateDNARequest
	(*ValidateDNAResponse)(nil), // 4: ValidateDNAResponse
}
var file_dna_proto_depIdxs = []int32{
	0, // 0: DNAResponse.dna:type_name -> DNA
	1, // 1: DnaGeneratorService.GetDNA:input_type -> DNARequest
	3, // 2: DnaGeneratorService.ValidateDNA:input_type -> ValidateDNARequest
	2, // 3: DnaGeneratorService.GetDNA:output_type -> DNAResponse
	4, // 4: DnaGeneratorService.ValidateDNA:output_type -> ValidateDNAResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dna_proto_init() }
func file_dna_proto_init() {
	if File_dna_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dna_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DNA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dna_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DNARequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dna_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DNAResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dna_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateDNARequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dna_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateDNAResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dna_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dna_proto_goTypes,
		DependencyIndexes: file_dna_proto_depIdxs,
		MessageInfos:      file_dna_proto_msgTypes,
	}.Build()
	File_dna_proto = out.File
	file_dna_proto_rawDesc = nil
	file_dna_proto_goTypes = nil
	file_dna_proto_depIdxs = nil
}
